# Generated by Django 5.1.5 on 2025-07-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
