# Generated by Django 5.1.5 on 2025-07-11 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management_app', '0002_alter_itemtype_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='shipping',
        ),
        migrations.AddField(
            model_name='shipping',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store_management_app.purchase'),
        ),
    ]
