# Generated by Django 5.1.5 on 2025-07-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management_app', '0003_rename_quantity_inventory_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='shipping_address',
            field=models.CharField(default='abc', max_length=255),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
