# Generated by Django 5.1.5 on 2025-07-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management_app', '0004_purchase_shipping_address_alter_itemtype_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='shipping_address',
            field=models.CharField(max_length=255),
        ),
    ]
