# Generated by Django 5.1.5 on 2025-07-16 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management_app', '0006_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store_management_app.customer'),
        ),
    ]
