# Generated by Django 5.1.5 on 2025-07-18 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management_app', '0007_purchase_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store_management_app.item'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.DeleteModel(
            name='PurchasedItem',
        ),
    ]
